/*
 * Copyright (c) 2011-2018, Meituan Dianping. All Rights Reserved.
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.dianping.zebra.filter;

import java.beans.PropertyChangeEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

import javax.sql.DataSource;

import com.dianping.zebra.group.config.datasource.entity.DataSourceConfig;
import com.dianping.zebra.group.datasources.FailOverDataSource;
import com.dianping.zebra.group.jdbc.GroupConnection;
import com.dianping.zebra.group.jdbc.GroupDataSource;
import com.dianping.zebra.shard.jdbc.ShardDataSource;
import com.dianping.zebra.shard.jdbc.ShardResultSet;
import com.dianping.zebra.shard.jdbc.ShardStatement;
import com.dianping.zebra.shard.router.RouterResult;
import com.dianping.zebra.single.jdbc.SingleConnection;
import com.dianping.zebra.single.jdbc.SingleDataSource;
import com.dianping.zebra.single.jdbc.SingleResultSet;
import com.dianping.zebra.single.jdbc.SingleStatement;

public class DefaultJdbcFilterChain implements JdbcFilter {
	protected final List<JdbcFilter> filters;

	protected int index = 0;

	public DefaultJdbcFilterChain(List<JdbcFilter> filters) {
		this.filters = filters;
	}

	@Override
	public void closeGroupConnection(GroupConnection source, JdbcFilter chain) throws SQLException {
		throw new UnsupportedOperationException();
	}

	@Override
	public void closeGroupDataSource(GroupDataSource source, JdbcFilter chain) throws SQLException {
		throw new UnsupportedOperationException();
	}

	@Override
	public void closeSingleConnection(SingleConnection source, JdbcFilter chain) throws SQLException {
		throw new UnsupportedOperationException();
	}

	@Override
	public void closeSingleDataSource(SingleDataSource source, JdbcFilter chain) throws SQLException {
		throw new UnsupportedOperationException();
	}

	@Override
	public <T> T executeSingleStatement(SingleStatement source, SingleConnection conn, String sql,
	      List<String> batchedSql, boolean isBatched, boolean autoCommit, Object params, JdbcFilter chain)
	      throws SQLException {
		throw new UnsupportedOperationException();
	}

	@Override
	public FailOverDataSource.FindMasterDataSourceResult findMasterFailOverDataSource(
	      FailOverDataSource.MasterDataSourceMonitor source, JdbcFilter chain) {
		throw new UnsupportedOperationException();
	}

	@Override
	public GroupConnection getGroupConnection(GroupDataSource source, JdbcFilter chain) throws SQLException {
		throw new UnsupportedOperationException();
	}

	@Override
	public int getOrder() {
		throw new UnsupportedOperationException();
	}

	@Override
	public SingleConnection getSingleConnection(SingleDataSource source, JdbcFilter chain) throws SQLException {
		throw new UnsupportedOperationException();
	}

	@Override
	public void init() {
		throw new UnsupportedOperationException();
	}

	@Override
	public void initGroupDataSource(GroupDataSource source, JdbcFilter chain) {
		throw new UnsupportedOperationException();
	}

	@Override
	public DataSource initSingleDataSource(SingleDataSource source, JdbcFilter chain) {
		throw new UnsupportedOperationException();
	}

	@Override
	public void refreshGroupDataSource(GroupDataSource source, String propertiesName, JdbcFilter chain) {
		throw new UnsupportedOperationException();
	}

	@Override
	public void switchFailOverDataSource(FailOverDataSource source, JdbcFilter chain) {
		throw new UnsupportedOperationException();
	}

	@Override
	public String processSQL(DataSourceConfig dsConfig, SQLProcessContext ctx, JdbcFilter chain) throws SQLException {
		throw new UnsupportedOperationException();
	}

	@Override
	public void closeSingleResultSet(SingleResultSet source, JdbcFilter chain) throws SQLException {
		throw new UnsupportedOperationException();
	}

	@Override
	public ResultSet executeShardQuery(ShardStatement source, String sql, JdbcFilter chain) throws SQLException {
		throw new UnsupportedOperationException();
	}

	@Override
	public int executeShardUpdate(ShardStatement source, String sql, int autoGeneratedKeys, int[] columnIndexes,
	      String[] columnNames, JdbcFilter chain) throws SQLException {
		throw new UnsupportedOperationException();
	}

	@Override
	public void shardRouting(RouterResult rr, JdbcFilter chain) throws SQLException {
		throw new UnsupportedOperationException();
	}

	@Override
	public void shardMerge(ShardResultSet rs, JdbcFilter chain) throws SQLException {
		throw new UnsupportedOperationException();
	}

	@Override
	public void configChanged(PropertyChangeEvent evt, JdbcFilter chain) {
		throw new UnsupportedOperationException();
	}

	@Override
	public void initShardDataSource(ShardDataSource source, JdbcFilter chain) {
		throw new UnsupportedOperationException();
	}
}